### ISSUE TITLE
Make not working - Kali 1.1.0a 64Bit

### ISSUE THREAD

**Issue by JohnnyAMD** [CoolerVoid/payloadmask#2]
Hi mate, 

I just wanted to got a look over the tool but trying to get it installeed over a Kali 1.1.0a x64 I'm getting an error message. 

I did nothing special but just followed the standard compilation steps from your doc: 

• wget https://github.com/CoolerVoid/payloadmask/archive/master.zip;
• unzip master.zip; cd payloadmask-master; make; ./payloadmask

Error message:
"
gcc -W -Wall -Wextra -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -c *.c
In file included from file_ops.c:2:0:
mem_ops.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
mem_ops.c:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
In file included from payloadmask.c:34:0:
mem_ops.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
In file included from string_ops.c:2:0:
mem_ops.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
In file included from tamper.c:2:0:
mem_ops.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
In file included from validate.c:34:0:
mem_ops.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
make: *** [0d1n] Error 1

Any ideas about how that could be solved out?

Thanks.

**Comment by CoolerVoid** [comment]
You need install library libcurl-dev or libcurl-devel
---
fatal error: curl/curl.h: No such file or directory
---

**Comment by JohnnyAMD** [comment]
Thanks mate. It worked :)

Cheers.
